"""Initial Migration

Revision ID: 03192e7d9544
Revises: f86804072547
Create Date: 2018-11-26 06:07:31.700439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03192e7d9544'
down_revision = 'f86804072547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog', sa.String(), nullable=True))
    op.drop_column('blogs', 'pitch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('pitch', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'blog')
    # ### end Alembic commands ###
