"""Initial Migration

Revision ID: 47f4ed3e4709
Revises: 1d5045b6400f
Create Date: 2018-11-25 21:30:04.730471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47f4ed3e4709'
down_revision = '1d5045b6400f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('prof_pic', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'profile')
    op.drop_column('users', 'prof_pic')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
