"""Initial Migration

Revision ID: deef51e5e2bf
Revises: 03192e7d9544
Create Date: 2018-11-26 06:20:08.014409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deef51e5e2bf'
down_revision = '03192e7d9544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'blogs', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('prof_pic', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'profile')
    op.drop_column('users', 'prof_pic')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    # ### end Alembic commands ###
